version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:266735821233:task-definition/poc_td:2"
        LoadBalancerInfo:
          ContainerName: "poc_cont"
          ContainerPort: 8080
Hooks:
  - BeforeInstall: "arn:aws:lambda:ap-south-1:266735821233:function:Before-install"
  - AfterInstall: "arn:aws:lambda:ap-south-1:266735821233:function:After-install"
  - AfterAllowTestTraffic: "arn:aws:lambda:ap-south-1:266735821233:function:AfterAllowTestTraffic"
