version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:149914652348:task-definition/Poc-td:1"  # ECS Task Definition ARN
        LoadBalancerInfo:
          ContainerName: "my-cont"  # Container name in ECS Task Definition
          ContainerPort: 8080  # Port the container listens
