version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:266735821233:task-definition/test-poc-td:1"
        LoadBalancerInfo:
          ContainerName: "test-poc-cont"
          ContainerPort: 8080
        DeploymentController:
          Type: CODE_DEPLOY
        DesiredCount: 2
